services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgres/data
    networks:
      - spring-boot-network
  spring-boot-app:
    container_name: spring-rest-api
    image: rest-api:v1
    ports:
      - "1234:9090"
    networks:
      - spring-boot-network
    depends_on:
      - postgres


volumes:
  postgres:

networks:
  spring-boot-network:
    driver: bridge